### ISSUE TITLE
Tomcat example required

### ISSUE THREAD

**Issue by aritrabasu104** [w20-framework/w20#84]
I need to deploy a W20 bridge application as an war to tomcat,Which I am able to.But the server is responding with a default html instead of configured one. An example will be a great help

**Comment by Sherpard** [comment]
If you refer to the masterpage, you can find the [oficial docs](http://seedstack.org/addons/w20-bridge/)

The property you're looking for is  **masterpageTemplate:** on your application.yaml
Hope it helps!

**Comment by Sherpard** [comment]
are you pointing to automatic configuration resource? 
`<html data-w20-app="${restPathSlash}/seed-w20/application/configuration">`

you can find a project that's working with w20 bridge [here](https://github.com/seedstack/hub)
you may need to [convert it to war](http://seedstack.org/guides/conversion-to-war/) if you intend to see a tomcat working app.

**Comment by aritrabasu104** [comment]
I am pointing to fragment.w20.json file, how to direct w20 bridge to fetch the Fragment configs?

**Comment by aritrabasu104** [comment]
This war is not working properly, fragment configs are not getting picked

**Comment by adrienlauer** [comment]
Hi!
Fragment manifest (*.w20.json) can only be picked by the W20 bridge when located in the classpath, so basically in `META-INF/resources`.

In a WAR you can also put fragments in the docroot (`src/main/webapp`) but they won't be detected. You have to configure them manually (with a full URL, not only the id) in the `w20.app.json` file.

Regarding the masterpage (homepage), the W20 bridge will automatically render a template located by default at the classpath location `org/seedstack/w20/masterpage.html`. Every official theme has a default masterpage. You can override it with a custom one. 

Documentation for the W20 bridge is [here](http://seedstack.org/addons/w20-bridge).
A full W20 bridge example can be found [here](https://github.com/seedstack/samples/tree/master/w20-bridge). This example is not a WAR so it doesn't show how to declare fragments in the docroot.

**Comment by Sherpard** [comment]
In order to get the fragments recognized, you need to include them on META-INF/resources folder, as [stated on Documentation](http://seedstack.org/addons/w20-bridge/#automatic-activation-of-fragments)
> Automatic activation of fragments #
The W20 bridge automatically detects W20 fragments (manifests ending with the .w20.json extension) present in the classpath under META-INF/resources and enables them in the generated W20 configuration.

> Note that the W20 bridge cannot detect fragments located outside the local classpath, like the ones in the document root or external to the application. Those fragments must still be explicitly specified in the W20 configuration.

after that, point your masterpage to the configuration resource

/seed-w20/application/configuration

**Comment by adrienlauer** [comment]
This issue was moved to seedstack/w20-bridge-addon#24
